// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8r09yADXJilRnIClke3ETiYt-_JbhAcc',
    appId: '1:320728653956:web:545a0a557760ed8bcf22d1',
    messagingSenderId: '320728653956',
    projectId: 'roti-bakar-amang-app',
    authDomain: 'roti-bakar-amang-app.firebaseapp.com',
    storageBucket: 'roti-bakar-amang-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7eIvjiJs5ZfQURaf7j3zNOUHen9RpSA',
    appId: '1:320728653956:android:817ccaec9522b3a3cf22d1',
    messagingSenderId: '320728653956',
    projectId: 'roti-bakar-amang-app',
    storageBucket: 'roti-bakar-amang-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVlqb293_XxpW3WlWyL-cnuQj5CcnOBpY',
    appId: '1:320728653956:ios:7cfb2e8428bc5ab9cf22d1',
    messagingSenderId: '320728653956',
    projectId: 'roti-bakar-amang-app',
    storageBucket: 'roti-bakar-amang-app.firebasestorage.app',
    iosBundleId: 'com.example.keuanganRoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVlqb293_XxpW3WlWyL-cnuQj5CcnOBpY',
    appId: '1:320728653956:ios:7cfb2e8428bc5ab9cf22d1',
    messagingSenderId: '320728653956',
    projectId: 'roti-bakar-amang-app',
    storageBucket: 'roti-bakar-amang-app.firebasestorage.app',
    iosBundleId: 'com.example.keuanganRoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8r09yADXJilRnIClke3ETiYt-_JbhAcc',
    appId: '1:320728653956:web:cd1104d2e3efffc2cf22d1',
    messagingSenderId: '320728653956',
    projectId: 'roti-bakar-amang-app',
    authDomain: 'roti-bakar-amang-app.firebaseapp.com',
    storageBucket: 'roti-bakar-amang-app.firebasestorage.app',
  );
}
